### ISSUE TITLE
Does not support IE11

### ISSUE THREAD

**Issue by kennethcurrie** [rubenillodo/windows-iana#21]
When using this package in IE11 the following error occurs:

"Error: Uncaught (in promise): TypeError: Object doesn't support property or method 'includes'
TypeError: Object doesn't support property or method 'includes'
   at Anonymous function (http://localhost:32971/dist/universal.d25b70be25402638eaea.js:183112:9)
   at Anonymous function (http://localhost:32971/dist/universal.d25b70be25402638eaea.js:60209:7)
   at find (http://localhost:32971/dist/universal.d25b70be25402638eaea.js:165439:5)
   at exports.findAlias (http://localhost:32971/dist/universal.d25b70be25402638eaea.js:183110:5)
   at exports.findWindows (http://localhost:32971/dist/universal.d25b70be25402638eaea.js:183093:5)
  --Project code --
   at createClass (http://localhost:32971/dist/universal.d25b70be25402638eaea.js:11296:13)
   at createDirectiveInstance (http://localhost:32971/dist/universal.d25b"

**Comment by rubenillodo** [comment]
Have you tried adding a polyfill for modern array methods? Babel should be able to deal with that, I think.

**Comment by kennethcurrie** [comment]
we're already using the core-js/es6/array polyfil, I suggestions to use this or the es7 polyfil to fix the includes error on SO.
